[package]
name = "charist"
version = "0.2.0"
edition = "2024"
description = "Bible reader app"
authors = ["Barbel"]
license = "AGPL-3"

# rust binaries are morbiously a beast
# this makes them smaller
[profile.release]
strip = true
lto = "fat"
codegen-units = 1
opt-level = "z"
panic = "abort"

[dependencies]
serde = {version = "=1.0.229", features = ["derive"]}
ciborium = "=0.2.2"
libcosmic = {
    git = "https://github.com/pop-os/libcosmic.git",
    rev = "a5267e623f356d1792cba7f480dd671cc8b52406",
    features = [
        "winit",
        "tokio",
        "iced_wgpu"
    ]
}
regex = "=1.13.1"
lazy_static = "=1.5.0"

[package.metadata.packager]
before-packaging-command = "cargo build --release"
product-name = "Charist"
identifier = "org.barbel.Charist"
icons = ["resources/icons/128x128.png"]
