[package]
name = "charist"
version = "0.3.0"
edition = "2024"
description = "Intuitive bible reader"
authors = ["Barbel"]
license = "AGPL-3"

# rust binaries are morbiously a beast
# this makes them smaller
[profile.release]
strip = true
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"

[profile.dev]
codegen-units = 256

[build-dependencies]
xdgen = "=0.1.0"

[dependencies]
serde = {version = "=1.0.229", features = ["derive"]}
ciborium = "=0.2.2"
regex = "=1.13.1"
lazy_static = "=1.5.0"
rust-embed = "=8.12.0"
i18n-embed = { version = "=0.16.0", features = ["fluent-system", "desktop-requester", ] }
i18n-embed-fl = "=0.10.1"
tantivy = "=0.26.1"
log = "0.4.33"

[target.'cfg(not(target_os = "windows"))'.dependencies]
libcosmic = { git = "https://github.com/pop-os/libcosmic.git", features = ["winit", "tokio", "wgpu"] }

# TODO a better fix than software rendering on windows
[target.'cfg(target_os = "windows")'.dependencies]
libcosmic = { git = "https://github.com/pop-os/libcosmic.git", features = ["winit", "tokio", "wgpu"] , default-features = false }
