[package]
name = "charist"
version = "0.3.0"
edition = "2024"
description = "Intuitive bible reader"
authors = ["Barbel"]
license = "AGPL-3"

# rust binaries are morbiously a beast
# this makes them smaller
[profile.release]
strip = true
lto = "fat"
codegen-units = 1
opt-level = "z"
panic = "abort"

[dependencies]
serde = {version = "=1.0.229", features = ["derive"]}
ciborium = "=0.2.2"
regex = "=1.13.1"
lazy_static = "=1.5.0"

[target.'cfg(not(target_os = "windows"))'.dependencies]
libcosmic = {
    git = "https://github.com/pop-os/libcosmic.git",
    rev = "a5267e623f356d1792cba7f480dd671cc8b52406",
    features = ["winit", "tokio"]
}

# TODO a better fix than software rendering on windows
[target.'cfg(target_os = "windows")'.dependencies]
libcosmic = {
    git = "https://github.com/pop-os/libcosmic.git",
    rev = "a5267e623f356d1792cba7f480dd671cc8b52406",
    features = ["winit", "tokio"] ,
    default-features = false
}

[package.metadata.deb]
maintainer = "Barbel"
copyright = "2026, Barbel"
extended-description = "An intuitive Bible reader desktop app built by Barbel."
depends = "$auto, libwayland-client0, libxkbcommon0"
section = "utility"
assets = [
    ["target/release/charist", "usr/bin/charist", "755"],
    ["resources/org.barbel.Charist.desktop", "usr/share/applications/", "644"],
    ["resources/icons/hicolor/scalable/apps/org.barbel.Charist.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/charist", dest = "/usr/bin/charist", mode = "755" },
    { source = "resources/org.barbel.Charist.desktop", dest = "/usr/share/applications/org.barbel.Charist.desktop", mode = "644" },
    { source = "resources/icons/hicolor/scalable/apps/org.barbel.Charist.svg", dest = "/usr/share/icons/hicolor/scalable/apps/org.barbel.Charist.svg", mode = "644" }
]
requires = { "wayland-libs" = "*", "libxkbcommon" = "*" }

[package.metadata.bundle]
icon = ["resources/icons/book.png"]
identifier = "org.barbel.Charist"
keywords = ["Bible", "Scripture", "Reader"]
category = "public.app-category.education"